---

- hosts: scigateway
  become: true
  vars:
    - icat_url: "https://scigateway-preprod.esc.rl.ac.uk:8181"
    - ids_url: "https://scigateway-preprod.esc.rl.ac.uk:8181"
  roles:
    - datagateway-download-api-mariadb
    - datagateway-download-api
    - scigateway-auth
    - datagateway-api
    - scigateway
    - datagateway
  handlers:
    - name: Restart apache
      service:
        name: httpd
        state: restarted
