---

- name: "Download"
  get_url:
    url: "https://github.com/ral-facilities/datagateway/releases/download/{{ datagateway_version }}/{{ item }}-{{ datagateway_version }}.tar.gz"
    dest: /root/{{ item }}-{{ datagateway_version }}.tar.gz
    force: "{{ datagateway_version == 'snapshot' }}"
  loop: "{{ datagateway_plugins }}"

- name: "Unarchive"
  unarchive:
    src: /root/{{ item }}-{{ datagateway_version }}.tar.gz
    dest: /root/
    remote_src: yes
    extra_opts: --no-same-owner
  loop: "{{ datagateway_plugins }}"

- name: "Check settings.json file existence"
  local_action: stat path="{{ lookup('vars', item + '_settings_file') }}"
  loop: "{{ datagateway_plugins }}"
  register: settingsFileResults
  become: false

- name: "Check strings file existence"
  local_action: stat path="{{ lookup('vars', item + '_strings_file') }}"
  loop: "{{ datagateway_plugins }}"
  register: stringsFileResults
  become: false

- name: "Check facility image existence"
  local_action: stat path={{ datagateway_facility_image }}
  register: facilityResult
  become: false
  when:
    - datagateway_facility_image is defined

- name: "Copy *-settings.json files"
  copy:
    src: "{{ item.stat.path }}"
    dest: /root/{{ item.item }}-{{ datagateway_version }}/{{ item.item }}-settings.json
    mode: 0644
  with_items: "{{ settingsFileResults.results }}"
  when:
    - item.stat.exists is defined
    - item.stat.exists == true

- name: "Create *-settings.json from templates"
  template:
    src: templates/{{ item.item }}-settings.json.j2
    dest: /root/{{ item.item }}-{{ datagateway_version }}/{{ item.item }}-settings.json
    mode: 0644
  with_items: "{{ settingsFileResults.results }}"
  when:
    - item.stat.exists is defined
    - item.stat.exists == false

- name: "Copy default.json"
  copy:
    src: "{{ item.stat.path }}"
    dest: /root/{{ item.item }}-{{ datagateway_version }}/res/default.json
    mode: 0644
  with_items: "{{ stringsFileResults.results }}"
  when:
    - item.stat.exists is defined
    - item.stat.exists == true

- name: "Copy facility image"
  copy:
    src: "{{ datagateway_facility_image }}"
    dest: /root/datagateway-dataview-{{ datagateway_version }}
    mode: 0644
  when:
   - datagateway_facility_image is defined
   - facilityResult.stat.exists is defined
   - facilityResult.stat.exists == true

- name: "Install to Scigateway plugins directory"
  copy:
    src: /root/{{ item }}-{{ datagateway_version }}/
    dest: "{{ scigateway_plugins_dir }}/{{ item }}"
    remote_src: yes
  loop: "{{ datagateway_plugins }}"

- name: "Rename main.js files to enable cache busting"
  copy:
    src: "{{ scigateway_plugins_dir }}/{{ item }}/main.js"
    dest: "{{ scigateway_plugins_dir }}/{{ item }}/main.{{ansible_date_time.epoch}}.js"
    remote_src: yes
  loop: "{{ datagateway_plugins }}"
