---

- name: "Download"
  get_url:
    url: "https://github.com/ral-facilities/datagateway/releases/download/{{ datagateway_version }}/{{ item }}-{{ datagateway_version }}.tar.gz"
    dest: /root/{{ item }}-{{ datagateway_version }}.tar.gz
    force: "{{ datagateway_version == 'snapshot' }}"
  loop: "{{ datagateway_plugins }}"

- name: "Unarchive"
  unarchive:
    src: /root/{{ item }}-{{ datagateway_version }}.tar.gz
    dest: /root/
    remote_src: yes
    extra_opts: --no-same-owner
  loop: "{{ datagateway_plugins }}"

- name: "Create *-settings.json from templates"
  template:
    src: templates/{{ item }}-settings.json.j2
    dest: /root/{{ item }}-{{ datagateway_version }}/{{ item }}-settings.json
    mode: 0644
  loop: "{{ datagateway_plugins }}"

- name: "Install to Scigateway plugins directory"
  copy:
    src: /root/{{ item }}-{{ datagateway_version }}/
    dest: "{{ scigateway_plugins_dir }}/{{ item }}"
    remote_src: yes
  loop: "{{ datagateway_plugins }}"
