---

- name: Set correct SELinux context for scigateway_auth_home & scigateway_auth_log
  community.general.sefcontext:
    target: '{{ item.target }}(/.*)?'
    setype: "{{ item.setype }}"
    state: present
    reload: True
  register: filecontext
  with_items:
  - { target: "{{ scigateway_auth_home }}", setype: "public_content_rw_t" }
  - { target: "{{ scigateway_auth_log }}", setype: "httpd_log_t" }
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'

- name: Apply new SELinux file contexts
  ansible.builtin.command: restorecon -Rv {{ item.target }}
  with_items:
  - { index: 0, target: "{{ scigateway_auth_home }}" }
  - { index: 1, target: "{{ scigateway_auth_log }}" }
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled' and filecontext.results[item.index] is changed

- name: "Create group"
  group:
    name: "{{ scigateway_auth_group }}"
    state: present

- name: "Create user"
  user:
    name: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    home: "{{ scigateway_auth_home }}"
    shell: /sbin/nologin
    system: yes

- name: "Create home directory"
  file:
    path: "{{ scigateway_auth_home }}"
    state: directory
    owner: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    mode: 0755

- name: "Create keys directory"
  file:
    path: "{{ scigateway_auth_home }}/keys"
    state: directory
    owner: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    mode: 0700

- name: "Create JWT private key"
  command:
    cmd: openssl genrsa -out {{ scigateway_auth_home }}/keys/jwt-key
    creates: "{{ scigateway_auth_home }}/keys/jwt-key"

- name: Change permissions of JWT private key
  ansible.builtin.file:
    path: "{{ scigateway_auth_home }}/keys/jwt-key"
    mode: '0644'

- name: "Create JWT public key"
  command:
    cmd: openssl rsa -in {{ scigateway_auth_home }}/keys/jwt-key -pubout -out {{ scigateway_auth_home }}/keys/jwt-key.pub
    creates: "{{ scigateway_auth_home }}/keys/jwt-key.pub"

- name: "Copy maintenance directory"
  copy:
    force: no
    src: files/maintenance
    dest: "{{ scigateway_auth_home }}"
    owner: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    mode: 0644
    directory_mode: 0755

- name: "Create log directory"
  file:
    path: "{{ scigateway_auth_log }}"
    state: directory
    owner: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    mode: 0755

- name: Install python3, pip, git, apache & mod files
  package:
    name:
      - python3
      - python3-pip
      - python-setuptools
      - git
      - httpd
      - mod_ssl
      - openssl
      - python3-mod_wsgi
    state: present

# Update pip first because older versions of pip will expect setup.py instead of pyproject.toml
- name: "Update pip in virtualenv"
  pip:
    name: pip
    state: latest
    virtualenv: "{{ scigateway_auth_virtualenv }}"
    virtualenv_command: python3 -m venv

- name: "Install into virtualenv"
  pip:
    name: "git+https://github.com/ral-facilities/scigateway-auth.git"
    state: latest
    virtualenv: "{{ scigateway_auth_virtualenv }}"
    virtualenv_python: python3
  notify:
  - Restart apache

- name: "Determine virtualenv site-packages directory"
  shell: "{{ scigateway_auth_virtualenv | quote }}/bin/pip3 show scigateway_auth | awk '/^Location:/ { print $2 }'"
  register: reg

- name: "Set value of scigateway_auth_site_packages"
  set_fact:
    scigateway_auth_site_packages: "{{ reg.stdout }}"

- name: "Check config.json file existence"
  local_action: stat path={{ scigateway_auth_config_file }}
  register: configFileResult
  become: false

- name: "Copy config.json"
  copy:
    src: "{{ scigateway_auth_config_file }}"
    dest: "{{ scigateway_auth_site_packages }}/scigateway_auth/config.json"
    mode: 0644
  when:
   - configFileResult.stat.exists is defined
   - configFileResult.stat.exists == true
  notify:
  - Restart apache

- name: "Create config.json from template"
  template:
    src: templates/config.json.j2
    dest: "{{ scigateway_auth_site_packages }}/scigateway_auth/config.json"
    owner: root
    group: root
    mode: 0644
  when:
   - configFileResult.stat.exists is defined
   - configFileResult.stat.exists == false
  notify:
  - Restart apache

- name: "Create apache conf fragment from template"
  set_fact:
    scigateway_auth_apache_conf: "{{ lookup('template', 'templates/apache.conf.j2') }}"
