---

- name: "Create group"
  group:
    name: "{{ scigateway_auth_group }}"
    state: present

- name: "Create user"
  user:
    name: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    home: "{{ scigateway_auth_home }}"
    shell: /sbin/nologin
    system: yes

- name: "Create home directory"
  file:
    path: "{{ scigateway_auth_home }}"
    state: directory
    owner: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    mode: 0755

- name: "Create keys directory"
  file:
    path: "{{ scigateway_auth_home }}/keys"
    state: directory
    owner: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    mode: 0700

- name: "Create JWT private key"
  command:
    cmd: openssl genrsa -out {{ scigateway_auth_home }}/keys/jwt-key
    creates: "{{ scigateway_auth_home }}/keys/jwt-key"

- name: "Create JWT public key"
  command:
    cmd: openssl rsa -in {{ scigateway_auth_home }}/keys/jwt-key -pubout -out {{ scigateway_auth_home }}/keys/jwt-key.pub
    creates: "{{ scigateway_auth_home }}/keys/jwt-key.pub"

- name: "Copy maintenance directory"
  copy:
    force: no
    src: files/maintenance
    dest: "{{ scigateway_auth_home }}"
    owner: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    mode: 0644
    directory_mode: 0755

- name: "Create log directory"
  file:
    path: "{{ scigateway_auth_log }}"
    state: directory
    owner: "{{ scigateway_auth_user }}"
    group: "{{ scigateway_auth_group }}"
    mode: 0755

- name: Install python3, pip, apache & mod files
  package:
    name:
      - python3
      - python3-pip
      - python3-devel
      - httpd
      - httpd-devel
      - mod_ssl
      - openssl
      - gcc
    state: present

- name: Install virtualenv and mod_wsgi
  pip:
    name:
     - virtualenv
     - mod_wsgi
    executable: pip3
    state: present

- name: Configure mod_wsgi
  shell: /usr/local/bin/mod_wsgi-express install-module >> /etc/httpd/conf.modules.d/00-wsgi.conf

# Update pip first because older versions of pip will expect setup.py instead of pyproject.toml
- name: "Update pip in virtualenv"
  pip:
    name: pip
    state: latest
    virtualenv: "{{ scigateway_auth_virtualenv }}"
    virtualenv_python: python3
    virtualenv_command: /usr/local/bin/virtualenv

- name: "Install into virtualenv"
  pip:
    name: "git+https://github.com/ral-facilities/scigateway-auth.git"
    state: latest
    virtualenv: "{{ scigateway_auth_virtualenv }}"
    virtualenv_python: python3

- name: "Determine virtualenv site-packages directory"
  shell: "{{ scigateway_auth_virtualenv | quote }}/bin/pip3 show scigateway_auth | awk '/^Location:/ { print $2 }'"
  register: reg

- name: "Set value of scigateway_auth_site_packages"
  set_fact:
    scigateway_auth_site_packages: "{{ reg.stdout }}"

- name: "Create config.json from template"
  template:
    src: templates/config.json.j2
    dest: "{{ scigateway_auth_site_packages }}/scigateway_auth/config.json"
    owner: root
    group: root
    mode: 0644

- name: "Create apache conf fragment from template"
  template:
    src: templates/apache.conf.j2
    dest: "/etc/httpd/conf.d/scigateway-auth.conf.fragment"
    owner: root
    group: root
    mode: 0644
