---

- name: "Create group"
  group:
    name: "{{ datagateway_api_group }}"
    state: present

- name: "Create user"
  user:
    name: "{{ datagateway_api_user }}"
    group: "{{ datagateway_api_group }}"
    home: "{{ datagateway_api_home }}"
    shell: /sbin/nologin
    system: yes

- name: "Create home directory"
  file:
    path: "{{ datagateway_api_home }}"
    state: directory
    owner: "{{ datagateway_api_user }}"
    group: "{{ datagateway_api_group }}"
    mode: 0755

- name: "Create log directory"
  file:
    path: "{{ datagateway_api_log }}"
    state: directory
    owner: "{{ datagateway_api_user }}"
    group: "{{ datagateway_api_group }}"
    mode: 0755

- name: Install python3, pip, apache & mod files
  package:
    name:
      - python3
      - python3-pip
      - python3-devel
      - httpd
      - httpd-devel
      - mod_ssl
      - openssl
      - gcc
    state: present

- name: Install virtualenv and mod_wsgi
  pip:
    name:
     - virtualenv
     - mod_wsgi
    executable: pip3
    state: present

- name: Check if mod_wsgi has already been configured
  stat:
    path: /etc/httpd/conf.modules.d/00-wsgi.conf
  register: stat_result

- name: Configure mod_wsgi
  shell: /usr/local/bin/mod_wsgi-express install-module >> /etc/httpd/conf.modules.d/00-wsgi.conf
  when: not stat_result.stat.exists

# Update pip first because older versions of pip will expect setup.py instead of pyproject.toml
- name: "Update pip in virtualenv"
  pip:
    name: pip
    state: latest
    virtualenv: "{{ datagateway_api_virtualenv }}"
    virtualenv_python: python3
    virtualenv_command: /usr/local/bin/virtualenv

- name: "Install into virtualenv"
  pip:
    name: "git+https://github.com/ral-facilities/datagateway-api.git"
    state: latest
    virtualenv: "{{ datagateway_api_virtualenv }}"
    virtualenv_python: python3

- name: "Determine virtualenv site-packages directory"
  shell: "{{ datagateway_api_virtualenv | quote }}/bin/pip3 show datagateway_api | awk '/^Location:/ { print $2 }'"
  register: reg

- name: "Set value of datagateway_api_site_packages"
  set_fact:
    datagateway_api_site_packages: "{{ reg.stdout }}"

- name: "Create config.json from template"
  template:
    src: templates/config.json.j2
    dest: "{{ datagateway_api_site_packages }}/datagateway_api/config.json"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart apache

- name: "Create apache conf fragment from template"
  template:
    src: templates/apache.conf.j2
    dest: "/etc/httpd/conf.d/datagateway-api.conf.fragment"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart apache
