---

- name: "Create install directory"
  file:
    path: "{{ scigateway_dir }}"
    state: directory
    mode: 0755

- name: "Create plugins directory"
  file:
    path: "{{ scigateway_plugins_dir }}"
    state: directory
    mode: 0755

- name: "Download"
  get_url:
    url: "https://github.com/ral-facilities/scigateway/releases/download/{{ scigateway_version }}/scigateway-{{ scigateway_version }}.tar.gz"
    dest: /root/scigateway-{{ scigateway_version }}.tar.gz
    force: "{{ scigateway_version == 'snapshot' }}"

- name: "Unarchive"
  unarchive:
    src: /root/scigateway-{{ scigateway_version }}.tar.gz
    dest: /root/
    remote_src: yes
    extra_opts: --no-same-owner

- name: "Check settings.json file existence"
  local_action: stat path={{ scigateway_settings_file }}
  register: settingsFileResult
  become: false

- name: "Check strings file existence"
  local_action: stat path={{ scigateway_strings_file }}
  register: stringsFileResult
  become: false

- name: "Check favicon existence"
  local_action: stat path={{ scigateway_favicon }}
  register: faviconResult
  become: false
  when:
    - scigateway_favicon is defined

- name: "Check logo existence"
  local_action: stat path={{ scigateway_logo }}
  register: logoResult
  become: false
  when:
    - scigateway_logo is defined

- name: "Copy settings.json"
  copy:
    src: "{{ scigateway_settings_file }}"
    dest: /root/scigateway-{{ scigateway_version }}/settings.json
    mode: 0644
  when:
   - settingsFileResult.stat.exists is defined
   - settingsFileResult.stat.exists == true

- name: "Create settings.json"
  template:
    src: templates/settings.json.j2
    dest: /root/scigateway-{{ scigateway_version }}/settings.json
    mode: 0644
  when:
   - settingsFileResult.stat.exists is defined
   - settingsFileResult.stat.exists == false

- name: "Edit settings.json to allow for cache busting of plugins"
  replace:
    path: /root/scigateway-{{ scigateway_version }}/settings.json
    regexp: '(^\s*"src": *".*)(\.js",\s?)'
    replace: '\1.{{ansible_date_time.epoch}}\2'

- name: "Copy default.json"
  copy:
    src: "{{ scigateway_strings_file }}"
    dest: /root/scigateway-{{ scigateway_version }}/res/default.json
    mode: 0644
  when:
   - stringsFileResult.stat.exists is defined
   - stringsFileResult.stat.exists == true

- name: "Edit title tag"
  replace:
    path: /root/scigateway-{{ scigateway_version }}/index.html
    after: '<title>'
    before: '</title>'
    regexp: '.*'
    replace: "{{ scigateway_title }}"

- name: "Replace favicon"
  copy:
    src: "{{ scigateway_favicon }}"
    dest: /root/scigateway-{{ scigateway_version }}/favicon.ico
    mode: 0644
  when:
   - scigateway_favicon is defined
   - faviconResult.stat.exists is defined
   - faviconResult.stat.exists == true

- name: "Copy logo"
  copy:
    src: "{{ scigateway_logo }}"
    dest: /root/scigateway-{{ scigateway_version }}
    mode: 0644
  when:
   - scigateway_logo is defined
   - logoResult.stat.exists is defined
   - logoResult.stat.exists == true

- name: "Edit manifest.json"
  replace:
    path: /root/scigateway-{{ scigateway_version }}/manifest.json
    regexp: '(^\s*"(?:short_name|name)": ").*(",?)$'
    replace: '\1{{ scigateway_title }}\2'

- name: "Install"
  copy:
    src: /root/scigateway-{{ scigateway_version }}/
    dest: "{{ scigateway_dir }}"
    remote_src: yes

- name: "Create apache conf from template"
  template:
    src: templates/apache.conf.j2
    dest: /etc/httpd/conf.d/scigateway.conf
    mode: 0644
  notify:
    - Restart apache

- name: Open port 443
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "443"
    jump: ACCEPT

- name: Open port 80
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "80"
    jump: ACCEPT

- name: Save iptables rules
  shell: iptables-save > /etc/sysconfig/iptables

- name: Start apache & ensure it starts on boot
  service:
    name: httpd
    state: started
    enabled: yes
