---

- name: "Create install directory"
  file:
    path: "{{ scigateway_dir }}"
    state: directory
    mode: 0755

- name: "Create plugins directory"
  file:
    path: "{{ scigateway_plugins_dir }}"
    state: directory
    mode: 0755

- name: "Download"
  get_url:
    url: "https://github.com/ral-facilities/scigateway/releases/download/{{ scigateway_version }}/scigateway-{{ scigateway_version }}.tar.gz"
    dest: /root/scigateway-{{ scigateway_version }}.tar.gz
    force: "{{ scigateway_version == 'snapshot' }}"

- name: "Unarchive"
  unarchive:
    src: /root/scigateway-{{ scigateway_version }}.tar.gz
    dest: /root/
    remote_src: yes
    extra_opts: --no-same-owner

- name: "Create settings.json"
  template:
    src: templates/settings.json.j2
    dest: /root/scigateway-{{ scigateway_version }}/settings.json
    mode: 0644

- name: "Install"
  copy:
    src: /root/scigateway-{{ scigateway_version }}/
    dest: "{{ scigateway_dir }}"
    remote_src: yes

- name: "Create apache conf from template"
  template:
    src: templates/apache.conf.j2
    dest: /etc/httpd/conf.d/scigateway.conf
    mode: 0644
  notify:
    - Restart apache

- name: "Add scigateway-auth config to apache conf"
  blockinfile:
    marker: "# {mark} scigateway-auth conf"
    block: "{{ lookup('file', '/etc/httpd/conf.d/scigateway-auth.conf.fragment') }}"
    path: /etc/httpd/conf.d/scigateway.conf
    insertbefore: "</VirtualHost>"
  notify:
    - Restart apache

- name: "Add datagateway-api config to apache conf"
  blockinfile:
    marker: "# {mark} datagateway-api conf"
    block: "{{ lookup('file', '/etc/httpd/conf.d/datagateway-api.conf.fragment') }}"
    path: /etc/httpd/conf.d/scigateway.conf
    insertbefore: "</VirtualHost>"
  notify:
    - Restart apache

- name: Start apache
  service:
    name: httpd
    state: started